use master
go
Create database [QLXetNghiem]
go
USE [QLXetNghiem]
GO
/****** Object: Table [dbo].[CONGTY] Script Date: 10/24/2021 09:50:05 
******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONGTY](
[MaCty] [nvarchar](6) NOT NULL,
[TenCty] [nvarchar](100) NOT NULL,
[SLNV] [int] NOT NULL,
CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED
(
[MaCty] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY =
OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CONGTY] ([MaCty], [TenCty], [SLNV]) VALUES (N'HITECH', N'HITECH WIRES ASIA', 1200)
INSERT [dbo].[CONGTY] ([MaCty], [TenCty], [SLNV]) VALUES (N'THANAM', N'SẢN 
XUẤT THƯƠNG MẠI DƯỢC PHẨM THÀNH NAM', 850)
INSERT [dbo].[CONGTY] ([MaCty], [TenCty], [SLNV]) VALUES (N'VISION',
N'VISION INTERNATIONAL', 5000)
/****** Object: Table [dbo].[NHANVIEN] Script Date: 10/24/2021 09:50:05 
******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
[ID] [nvarchar](12) NOT NULL,
[HoTen] [nvarchar](200) NOT NULL,
[SoLanXN] [int] NOT NULL,
[AmTinh] [bit] NOT NULL,
[MaCty] [nvarchar](6) NOT NULL,
CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED
(
[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY =
OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[NHANVIEN] ([ID], [HoTen], [SoLanXN], [AmTinh], [MaCty]) VALUES 
(N'026087011432', N'Nguyễn Văn D', 1, 1, N'VISION')
INSERT [dbo].[NHANVIEN] ([ID], [HoTen], [SoLanXN], [AmTinh], [MaCty]) VALUES 
(N'036284010260', N'Nguyễn Văn C', 2, 0, N'HITECH')
INSERT [dbo].[NHANVIEN] ([ID], [HoTen], [SoLanXN], [AmTinh], [MaCty]) VALUES 
(N'240837639', N'Nguyễn Văn A', 1, 1, N'VISION')
INSERT [dbo].[NHANVIEN] ([ID], [HoTen], [SoLanXN], [AmTinh], [MaCty]) VALUES 
(N'241233818', N'Nguyễn Văn B', 2, 0, N'THANAM')
/****** Object: ForeignKey [FK_NHANVIEN_CONGTY] Script Date: 10/24/2021 
09:50:05 ******/
ALTER TABLE [dbo].[NHANVIEN] WITH CHECK ADD CONSTRAINT
[FK_NHANVIEN_CONGTY] FOREIGN KEY([MaCty])
REFERENCES [dbo].[CONGTY] ([MaCty])
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_CONGTY]
GO