// <auto-generated />
namespace RapPhimNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addtablekhachhanghoadonchitiet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablekhachhanghoadonchitiet));
        
        string IMigrationMetadata.Id
        {
            get { return "202208040727310_add-table-khachhang-hoadon-chitiet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
