// <auto-generated />
namespace RapPhimNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTable_Quyen_PhanQuyen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTable_Quyen_PhanQuyen));
        
        string IMigrationMetadata.Id
        {
            get { return "202207300617083_AddTable_Quyen_PhanQuyen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
